name: Fork Merge

on:
 schedule:
 - cron: 0 * * * *

jobs:

 sfall:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@master
    with:
     fetch-depth: 1

  - name: Fork Merge
    run:  ./fork-merge.sh "https://github.com/phobos2077/sfall.git" "https://github.com/rotators/sfall.git" "$ANTALASKAYA_TOKEN" master develop 3.8-maintenance
    env:
     ANTALASKAYA_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}
