#
# TODO this should be made into legit action some day if we want to mirror more repos...
#      ... but we'd have to use js <thunder.wav> ...
#      ...or wait when/if https://github.community/t5/GitHub-Actions/Feature-request-Shell-script-as-type-of-action/m-p/30671#M506 is added
#
# - uses: rotators/gha-fork/mirror@???
#   with:
#    upstream:   https://github.com/cvet/fonline.git
#    fork:       rotators/fonline
#    user:       antalaskaya
#    token:      ${{ secrets.ANTALASKAYA_TOKEN }}
#

name: Fork Mirror

on:
 schedule:
 - cron: 0 * * * *

jobs:

 fonline:
  runs-on: ubuntu-latest

  steps:
  - name: clone
    run:  git clone --mirror https://github.com/cvet/fonline.git . && pwd && ls

  # add custom fetch filtering
  - name: patch config
    run:  |
          git config --unset remote.origin.fetch
          git config --add remote.origin.fetch +refs/heads/*:refs/heads/*
          git config --add remote.origin.fetch +refs/tags/*:refs/tags/*
          cat config

  - name: add remote
    run:  |
          git remote add fork https://antalaskaya:$ANTALASKAYA_TOKEN@github.com/rotators/fonline.git
          git config --unset remote.fork.fetch
          git config --add remote.fork.mirror true
    env:
     ANTALASKAYA_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}

  # remove upstream pull requests
  # must be done, as clone --mirror grabbed pull requests refs before we added fetch filtering to config
  # NOTE: other hosters uses different names, eg. bitbucket: 'pull-request')
  - name: remove pull requests
    run:  |
          git show-ref | cut -d' ' -f2 | grep 'pull' | xargs -r -L1 git update-ref -d
          git show-ref

  - name: synch
    run:  git fetch --prune

  - name: push
    run:  git push --prune fork

 ###

 fonline-historical-stuff:
  runs-on: ubuntu-latest
  needs: fonline

  steps:
  - name: clone
    run:  git clone --mirror https://github.com/cvet/fonline-historical-stuff.git . && pwd && ls

  # add custom fetch filtering
  - name: patch config
    run:  |
          git config --unset remote.origin.fetch
          git config --add remote.origin.fetch +refs/heads/*:refs/heads/*
          git config --add remote.origin.fetch +refs/tags/*:refs/tags/*
          cat config

  - name: add remote
    run:  |
          git remote add fork https://antalaskaya:$ANTALASKAYA_TOKEN@github.com/rotators/fonline-historical-stuff.git
          git config --unset remote.fork.fetch
          git config --add remote.fork.mirror true
    env:
     ANTALASKAYA_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}

  # remove upstream pull requests
  # must be done, as clone --mirror grabbed pull requests refs before we added fetch filtering to config
  # NOTE: other hosters uses different names, eg. bitbucket: 'pull-request')
  - name: remove pull requests
    run:  |
          git show-ref | cut -d' ' -f2 | grep 'pull' | xargs -r -L1 git update-ref -d
          git show-ref

  - name: synch
    run:  git fetch --prune

  - name: push
    run:  git push --prune fork
